#!/usr/bin/env bash
# Pull Shark Farm — automated PR harvester
# Usage: ./farm.sh [START] [END]
#   START  first PR number (default: auto-detect from pull-shark-log.md)
#   END    last PR number  (default: 1024)

set -euo pipefail

LOG_FILE="pull-shark-log.md"
START="${1:-}"
END="${2:-1024}"

# ── auto-detect start if not provided ─────────────────────────────────────────
if [[ -z "$START" ]]; then
  if [[ -f "$LOG_FILE" ]]; then
    LAST=$(grep -oE '^PR [0-9]+' "$LOG_FILE" | awk '{print $2}' | sort -n | tail -1)
    START=$(( ${LAST:-0} + 1 ))
  else
    START=1
  fi
fi

echo "🦈  Pull Shark Farm: PRs $START → $END"
echo "─────────────────────────────────────────"

for i in $(seq "$START" "$END"); do
  echo ""
  echo "▶ PR $i / $END"

  git checkout main
  git pull origin main

  branch="pull-shark-$i"
  git checkout -b "$branch"

  echo "PR $i: $(date)" >> "$LOG_FILE"
  git add "$LOG_FILE"
  git commit -m "Add pull shark log $i"

  git push -u origin "$branch"

  gh pr create \
    --title "Pull Shark PR $i" \
    --body "$(cat <<EOF
## Summary

Automated harvest entry **#$i** — keeping the farm running.

| Field  | Value |
|--------|-------|
| Entry  | $i / $END |
| Date   | $(date -u +"%Y-%m-%dT%H:%M:%SZ") |

---
*Generated by [Pull Shark Farm](https://github.com/Tivo0921/pull-shark-farm)*
EOF
)" \
    --base main \
    --head "$branch"

  gh pr merge "$branch" --merge --delete-branch

  echo "✓  PR $i merged"
done

echo ""
echo "🎉  All done! PRs $START–$END harvested."
